version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app
  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    ports:
      - 3000:3000
    depends_on:
      - adminer
      - postgres
    command: [ sh, -c, 'npm run start:dev' ]
    volumes:
      - .:/app
      - /app/node_modules
networks:
  app:
