export type CodeMessageProps = {
    subject: string,
    welcome: string,
    introduction: string,
    yourCode: string,
    code: string,
    aboutCode: string,
    expiringDate: string,
    warning: string,
    mediaHeading: string,
    facebookLink: string,
    instagramLink: string,
    discordLink: string,
    websiteLink: string,
}