export enum LogsTypes {
    INTERNAL_ACTION_FAIL = "INTERNAL_ACTION_FAIL",
    INTERNAL_ACTION = "INTERNAL_ACTION",
    CHANNEL_CREATED = "CHANNEL_CREATED",
    CHANNEL_REMOVED = "CHANNEL_REMOVED",
    USER_JOINED = "USER_JOINED",
    USER_LEFT = "USER_LEFT",
    PERMISSIONS_FAIL = "PERMISSIONS_FAIL",
    PERMISSIONS_GRANTED = "PERMISSIONS_GRANTED",
    PERMISSIONS_REVOKED = "PERMISSIONS_REVOKED",
    DATABASE_FAIL = "DATABASE_FAIL",
    DATABASE_READ = "DATABASE_READ",
    DATABASE_WRITE = "DATABASE_WRITE",
}