export enum AppServices {
    CHANNELS_SERVICE = `CHANNELS_SERVICE`,
    MESSAGES_SERVICE = `MESSAGES_SERVICE`,
    MEMBERS_SERVICE = `MEMBERS_SERVICE`,
    ROLES_SERVICE = `ROLES_SERVICE`,
    ALL = `ALL`
}